b'--- ./yt_dlp/utils/progress.py\t(original)'
b'+++ ./yt_dlp/utils/progress.py\t(refactored)'
b'@@ -1,3 +1,6 @@'
b'+from __future__ import division'
b'+from __future__ import with_statement'
b'+from __future__ import absolute_import'
b' from __future__ import annotations'
b' '
b' import bisect'
b'@@ -5,7 +8,7 @@'
b' import time'
b' '
b' '
b'-class ProgressCalculator:'
b'+class ProgressCalculator(object):'
b'     # Time to calculate the speed over (seconds)'
b'     SAMPLING_WINDOW = 3'
b'     # Minimum timeframe before to sample next downloaded bytes (seconds)'
b'@@ -13,7 +16,7 @@'
b'     # Time before showing eta (seconds)'
b'     GRACE_PERIOD = 1'
b' '
b'-    def __init__(self, initial: int):'
b'+    def __init__(self, initial):'
b'         self._initial = initial or 0'
b'         self.downloaded = self._initial'
b' '
b'@@ -36,7 +39,7 @@'
b'         return self._total'
b' '
b'     @total.setter'
b'-    def total(self, value: int | None):'
b'+    def total(self, value):'
b'         with self._lock:'
b'             if value is not None and value < self.downloaded:'
b'                 value = self.downloaded'
b'@@ -48,7 +51,7 @@'
b'         with self._lock:'
b'             self._thread_sizes[current_thread] = 0'
b' '
b'-    def update(self, size: int | None):'
b'+    def update(self, size):'
b'         if not size:'
b'             return'
b' '
b'@@ -59,7 +62,7 @@'
b'             self._thread_sizes[current_thread] = size'
b'             self._update(size - last_size)'
b' '
b'-    def _update(self, size: int):'
b'+    def _update(self, size):'
b'         current_time = time.monotonic()'
b' '
b'         self.downloaded += size'
b'@@ -93,12 +96,12 @@'
b'             self.eta.reset()'
b' '
b' '
b'-class SmoothValue:'
b'-    def __init__(self, initial: float | None, smoothing: float):'
b'+class SmoothValue(object):'
b'+    def __init__(self, initial, smoothing):'
b'         self.value = self.smooth = self._initial = initial'
b'         self._smoothing = smoothing'
b' '
b'-    def set(self, value: float):'
b'+    def set(self, value):'
b'         self.value = value'
b'         if self.smooth is None:'
b'             self.smooth = self.value'
