b'--- ./yt_dlp/version.py\t(original)'
b'+++ ./yt_dlp/version.py\t(refactored)'
b'@@ -1,15 +1,15 @@'
b' # Autogenerated by devscripts/update-version.py'
b' '
b"-__version__ = '2025.08.22'"
b"+__version__ = u'2025.08.22'"
b' '
b"-RELEASE_GIT_HEAD = '5c8bcfdbc638dfde13e93157637d8521413ed774'"
b"+RELEASE_GIT_HEAD = u'5c8bcfdbc638dfde13e93157637d8521413ed774'"
b' '
b' VARIANT = None'
b' '
b' UPDATE_HINT = None'
b' '
b"-CHANNEL = 'stable'"
b"+CHANNEL = u'stable'"
b' '
b"-ORIGIN = 'yt-dlp/yt-dlp'"
b"+ORIGIN = u'yt-dlp/yt-dlp'"
b' '
b"-_pkg_version = '2025.08.22'"
b"+_pkg_version = u'2025.08.22'"
