# Autogenerated by devscripts/update-version.py

__version__ = u'2025.08.22'

RELEASE_GIT_HEAD = u'5c8bcfdbc638dfde13e93157637d8521413ed774'

VARIANT = None

UPDATE_HINT = None

CHANNEL = u'stable'

ORIGIN = u'yt-dlp/yt-dlp'

_pkg_version = u'2025.08.22'
