b'--- ./devscripts/update-version.py\t(original)'
b'+++ ./devscripts/update-version.py\t(refactored)'
b'@@ -1,6 +1,8 @@'
b' #!/usr/bin/env python3'
b' '
b' # Allow direct execution'
b'+from __future__ import with_statement'
b'+from __future__ import absolute_import'
b' import os'
b' import sys'
b' '
b'@@ -17,24 +19,24 @@'
b' '
b' def get_new_version(version, revision):'
b'     if not version:'
b"-        version = dt.datetime.now(dt.timezone.utc).strftime('%Y.%m.%d')"
b"+        version = dt.datetime.now(dt.timezone.utc).strftime(u'%Y.%m.%d')"
b' '
b'     if revision:'
b"-        assert revision.isdecimal(), 'Revision must be a number'"
b"+        assert revision.isdecimal(), u'Revision must be a number'"
b'     else:'
b"-        old_version = read_version().split('.')"
b"-        if version.split('.') == old_version[:3]:"
b'-            revision = str(int(([*old_version, 0])[3]) + 1)'
b"+        old_version = read_version().split(u'.')"
b"+        if version.split(u'.') == old_version[:3]:"
b'+            revision = unicode(int(([*old_version, 0])[3]) + 1)'
b' '
b"     return f'{version}.{revision}' if revision else version"
b' '
b' '
b' def get_git_head():'
b'     with contextlib.suppress(Exception):'
b"-        return run_process('git', 'rev-parse', 'HEAD').stdout.strip()"
b"+        return run_process(u'git', u'rev-parse', u'HEAD').stdout.strip()"
b' '
b' '
b"-VERSION_TEMPLATE = '''\\"
b"+VERSION_TEMPLATE = u'''\\"
b' # Autogenerated by devscripts/update-version.py'
b' '
b' __version__ = {version!r}'
b'@@ -52,31 +54,31 @@'
b' _pkg_version = {package_version!r}'
b" '''"
b' '
b"-if __name__ == '__main__':"
b"-    parser = argparse.ArgumentParser(description='Update the version.py file')"
b"+if __name__ == u'__main__':"
b"+    parser = argparse.ArgumentParser(description=u'Update the version.py file')"
b'     parser.add_argument('
b"-        '-c', '--channel', default='stable',"
b"-        help='Select update channel (default: %(default)s)')"
b"+        u'-c', u'--channel', default=u'stable',"
b"+        help=u'Select update channel (default: %(default)s)')"
b'     parser.add_argument('
b"-        '-r', '--origin', default='local',"
b"-        help='Select origin/repository (default: %(default)s)')"
b"+        u'-r', u'--origin', default=u'local',"
b"+        help=u'Select origin/repository (default: %(default)s)')"
b'     parser.add_argument('
b"-        '-s', '--suffix', default='',"
b'-        help=\'Add an alphanumeric suffix to the package version, e.g. "dev"\')'
b"+        u'-s', u'--suffix', default=u'',"
b'+        help=u\'Add an alphanumeric suffix to the package version, e.g. "dev"\')'
b'     parser.add_argument('
b"-        '-o', '--output', default='yt_dlp/version.py',"
b"-        help='The output file to write to (default: %(default)s)')"
b"+        u'-o', u'--output', default=u'yt_dlp/version.py',"
b"+        help=u'The output file to write to (default: %(default)s)')"
b'     parser.add_argument('
b"-        'version', nargs='?', default=None,"
b"-        help='A version or revision to use instead of generating one')"
b"+        u'version', nargs=u'?', default=None,"
b"+        help=u'A version or revision to use instead of generating one')"
b'     args = parser.parse_args()'
b' '
b'     git_head = get_git_head()'
b'     version = ('
b"-        args.version if args.version and '.' in args.version"
b"+        args.version if args.version and u'.' in args.version"
b'         else get_new_version(None, args.version))'
b'     write_file(args.output, VERSION_TEMPLATE.format('
b'         version=version, git_head=git_head, channel=args.channel, origin=args.origin,'
b"         package_version=f'{version}{args.suffix}'))"
b' '
b"-    print(f'version={version} ({args.channel}), head={git_head}')"
b"+    print f'version={version} ({args.channel}), head={git_head}'"
